In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
recipe_details_df = pd.read_csv("CulinaryDB/01_Recipe_Details.csv")

In [3]:
recipe_details_df.head()

Recipe ID                         Title       Source              Cuisine
0          1  5 spice vegetable fried rice  TARLA_DALAL  Indian Subcontinent
1          2                  aachar aaloo  TARLA_DALAL  Indian Subcontinent
2          3    aadu lassan keri nu athanu  TARLA_DALAL  Indian Subcontinent
3          4                   aaloo kofta  TARLA_DALAL  Indian Subcontinent
4          5           aaloo tamatar subzi  TARLA_DALAL  Indian Subcontinent

## User Interaction data

In [5]:
user_id = [x for x in range(1, 251)]

In [13]:
mean_value = 30
std = 13
sessions_initiated = np.round(np.abs(np.random.normal(loc= mean_value, scale=std, size=250)))
sessions_initiated

array([40., 36., 16., 27., 55.,  6., 35., 29., 21., 13., 31., 28., 27.,
       37.,  8.,  9., 21., 32., 18., 37., 56., 39., 30., 28., 20., 35.,
       34., 21., 36., 26., 35., 29., 25., 29., 37., 22., 54., 28., 42.,
       24., 31., 27., 39., 43., 15., 29., 27., 13., 45., 24.,  3., 12.,
       59., 23., 23., 10., 26., 29.,  4., 27., 22., 22., 18., 44., 18.,
       17., 25., 30., 31., 43.,  3., 49., 11., 15., 21., 46., 28., 19.,
       28., 39., 30., 46., 42., 38., 26., 40., 24., 17., 23., 29., 20.,
       17., 49., 23., 20., 39., 26., 33., 46., 34., 20., 54., 37., 40.,
       37., 23., 46., 51., 34., 39., 26., 32., 24., 44., 11., 15., 50.,
       46., 43., 24., 10., 21., 30., 36., 33., 32., 41., 41., 50., 40.,
       26., 33., 64., 42., 29., 18., 36.,  6., 61., 20., 15., 18., 33.,
       31., 44., 29., 23., 35., 20., 26., 32., 29., 13., 12., 34., 43.,
       32., 57., 49., 26., 50., 14., 33., 28., 22., 32., 50., 52., 15.,
        2., 20., 42., 18., 40., 23., 35., 32., 42., 36., 31., 12

In [18]:
sessions_initiated = sessions_initiated.astype(int)
sessions_initiated

array([40, 36, 16, 27, 55,  6, 35, 29, 21, 13, 31, 28, 27, 37,  8,  9, 21,
       32, 18, 37, 56, 39, 30, 28, 20, 35, 34, 21, 36, 26, 35, 29, 25, 29,
       37, 22, 54, 28, 42, 24, 31, 27, 39, 43, 15, 29, 27, 13, 45, 24,  3,
       12, 59, 23, 23, 10, 26, 29,  4, 27, 22, 22, 18, 44, 18, 17, 25, 30,
       31, 43,  3, 49, 11, 15, 21, 46, 28, 19, 28, 39, 30, 46, 42, 38, 26,
       40, 24, 17, 23, 29, 20, 17, 49, 23, 20, 39, 26, 33, 46, 34, 20, 54,
       37, 40, 37, 23, 46, 51, 34, 39, 26, 32, 24, 44, 11, 15, 50, 46, 43,
       24, 10, 21, 30, 36, 33, 32, 41, 41, 50, 40, 26, 33, 64, 42, 29, 18,
       36,  6, 61, 20, 15, 18, 33, 31, 44, 29, 23, 35, 20, 26, 32, 29, 13,
       12, 34, 43, 32, 57, 49, 26, 50, 14, 33, 28, 22, 32, 50, 52, 15,  2,
       20, 42, 18, 40, 23, 35, 32, 42, 36, 31, 12,  7, 24, 28, 31, 37, 18,
       14, 36, 16, 22, 24,  6, 19, 59,  8, 17, 22, 38, 11, 19, 12, 32, 44,
       28, 25, 37, 55,  6, 10, 58, 10, 57, 44, 15, 34, 25, 20, 41, 38,  3,
       35, 18, 26, 33, 19

In [26]:
mean_value = 12
std = 4
average_time_per_session = np.round(np.abs(np.random.normal(loc= mean_value, scale=std, size=250)), decimals= 1)
average_time_per_session

array([12.3, 19.7, 12.1, 14.5, 18.5,  9.9,  2.9, 13.6, 11.2, 10. ,  8.7,
       13. , 11.6, 13.6, 13.9,  9. , 13.6,  6.9, 11.6, 16.6, 10. , 16.7,
       13.1, 16. , 11.2, 15.4,  7.1, 12.1, 12.9, 19.3, 18.3, 16.3, 12.3,
       10.1, 10.7, 11.9,  9.6, 12.4, 10.9,  7.5, 12.4, 14. , 11.9, 15.8,
       13.7, 14.6, 15.9, 11.4, 10.8, 17.5,  9.2,  9.6, 11.2, 15.4, 15.2,
        6.7, 10.9, 10.9, 17.4, 11.2, 18.4,  9. , 12. ,  7.8, 14.3, 11.5,
        7. , 13.8, 16.5,  8.5, 10.3, 10.9, 23.5, 12.6, 14. ,  7.9, 18.5,
        8.7, 10.5,  7.5, 12.1,  8.4, 13. , 11.8, 14. , 17. , 11.5,  5.8,
       10.2,  8.5,  8.4, 12.8,  9.3, 10.4,  4.5,  6.1,  8.1,  8.5, 10.3,
        8.6, 11.4,  7.2, 12.9,  5.7, 13.3,  6.5,  8.6, 12.3, 15.6, 12.2,
        7.3,  5.3, 10.8, 13.5, 13.9, 12.7,  5.8, 12. , 10.2, 11. , 24.9,
        7.8, 21.7, 16.9, 12.8, 14.1,  9.1,  8.1, 13.2, 15.5, 11.4,  9.7,
       15.9,  7.7, 12.4, 11. , 15.2,  9.2, 16.2, 12.3, 14. , 12. ,  3.2,
        8.9,  9.9, 11.5, 16.3,  7.6, 15. , 20.5, 10

In [ ]:
favourite_recipes = []
recipe_details_df

In [32]:
recipe_details_df['Title'].sample(4).values

array(['Cornmeal Thumbprint Cookies with Summer Strawberry Jam',
       'Roasted Garlic Green Hummus', 'Rice Salad Italienne',
       'Kataifi with Candied Pumpkin and Yogurt'], dtype=object)